
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setTitle("Inicio"); // Cambia el título de la ventana
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btn_categorias = new javax.swing.JButton();
        btn_obras = new javax.swing.JButton();
        btn_artistas = new javax.swing.JButton();
        btn_expos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_categorias.setBackground(new java.awt.Color(255, 204, 204));
        btn_categorias.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_categorias.setText("Ver categorías");
        btn_categorias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_categorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_categoriasActionPerformed(evt);
            }
        });
        jPanel2.add(btn_categorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 160, 40));

        btn_obras.setBackground(new java.awt.Color(255, 204, 204));
        btn_obras.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_obras.setText("Ver obras");
        btn_obras.setBorder(null);
        btn_obras.setBorderPainted(false);
        btn_obras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_obras.setRequestFocusEnabled(false);
        btn_obras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_obrasActionPerformed(evt);
            }
        });
        jPanel2.add(btn_obras, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 160, 40));

        btn_artistas.setBackground(new java.awt.Color(255, 204, 204));
        btn_artistas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_artistas.setText("Ver artistas");
        btn_artistas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_artistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_artistasActionPerformed(evt);
            }
        });
        jPanel2.add(btn_artistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 160, 40));

        btn_expos.setBackground(new java.awt.Color(255, 204, 204));
        btn_expos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_expos.setText("Ver exposiciones");
        btn_expos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_expos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exposActionPerformed(evt);
            }
        });
        jPanel2.add(btn_expos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 160, 40));

        jLabel2.setBackground(new java.awt.Color(51, 0, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("GALERIA ARTE");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/art.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_categoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_categoriasActionPerformed
     
        this.dispose();
        Categorias categorias = new Categorias();
        categorias.setVisible(true);
    }//GEN-LAST:event_btn_categoriasActionPerformed

    private void btn_obrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_obrasActionPerformed
        this.dispose();
        Obras obras = new Obras();
        obras.setVisible(true);
    }//GEN-LAST:event_btn_obrasActionPerformed

    private void btn_exposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exposActionPerformed
      
        this.dispose();
        Exposiciones exposiciones = new Exposiciones();
        exposiciones.setVisible(true);
    }//GEN-LAST:event_btn_exposActionPerformed

    private void btn_artistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_artistasActionPerformed
    
        this.dispose();
        Artistas artistas = new Artistas();
        artistas.setVisible(true);
    }//GEN-LAST:event_btn_artistasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_artistas;
    private javax.swing.JButton btn_categorias;
    private javax.swing.JButton btn_expos;
    private javax.swing.JButton btn_obras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
